In [2]:
import pandas as pd
import numpy as np

In [9]:
df_gdp = pd.read_csv("../data/cleaned/gdp_clean.csv")
df_income = pd.read_csv("../data/cleaned/income_pc_clean.csv")
df_real_income = pd.read_csv("../data/cleaned/real_income_pc_clean.csv")
df_rpp = pd.read_csv("../data/cleaned/regional_price_parity_clean.csv")

In [ ]:
df_gdp["Year"].unique()

array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [ ]:
for i in range(1997,2008):
    df = df[df["Year"]!= i]

1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007


In [20]:
df_income["Year"].unique()

array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [21]:
df_real_income["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [22]:
df_rpp["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [15]:
df = df_gdp.merge(df_income, on=["State", "Year"], how="outer")
df = df.merge(df_real_income, on=["State", "Year"], how="outer")
df = df.merge(df_rpp, on=["State", "Year"], how="outer")

In [16]:
df.head()

,State,Year,GDP,Income_pc,Real_Income_pc,RPP
0,Alabama,1997,105381.4,21487.0,NaN,NaN
1,Alabama,1998,110838.8,22651.0,NaN,NaN
2,Alabama,1999,116514.3,23296.0,NaN,NaN
3,Alabama,2000,120522.6,24258.0,NaN,NaN
4,Alabama,2001,123534.5,25046.0,NaN,NaN


In [26]:
for i in range(1997,2008):
    df = df[df["Year"]!= i]

In [27]:
df.head()

,State,Year,GDP,Income_pc,Real_Income_pc,RPP
11,Alabama,2008,174665.6,33441.0,42219.0,88.901
12,Alabama,2009,170876.5,32717.0,41966.0,87.786
13,Alabama,2010,177510.7,33848.0,41709.0,89.783
14,Alabama,2011,182896.7,34884.0,41819.0,90.011
15,Alabama,2012,188280.7,35559.0,41592.0,90.559


In [28]:
df.tail()

,State,Year,GDP,Income_pc,Real_Income_pc,RPP
1423,Wyoming,2020,36982.7,65093.0,67906.0,91.836
1424,Wyoming,2021,42410.6,71459.0,71860.0,91.440
1425,Wyoming,2022,49570.4,77768.0,73081.0,91.767
1426,Wyoming,2023,51350.1,83038.0,75323.0,91.551
1427,Wyoming,2024,51498.1,86477.0,75501.0,92.691


In [29]:
df.head(50)

,State,Year,GDP,Income_pc,Real_Income_pc,RPP
11,Alabama,2008,174665.6,33441.0,42219.0,88.901
12,Alabama,2009,170876.5,32717.0,41966.0,87.786
13,Alabama,2010,177510.7,33848.0,41709.0,89.783
14,Alabama,2011,182896.7,34884.0,41819.0,90.011
15,Alabama,2012,188280.7,35559.0,41592.0,90.559
16,Alabama,2013,193981.5,35706.0,41325.0,90.324
17,Alabama,2014,197064.4,36722.0,41984.0,90.175
18,Alabama,2015,203113.3,38189.0,43809.0,89.741
19,Alabama,2016,208824.3,38704.0,43554.0,90.609
20,Alabama,2017,216615.5,39968.0,44481.0,90.065


In [30]:
df = df.reset_index(drop=True)

In [31]:
df.head()

,State,Year,GDP,Income_pc,Real_Income_pc,RPP
0,Alabama,2008,174665.6,33441.0,42219.0,88.901
1,Alabama,2009,170876.5,32717.0,41966.0,87.786
2,Alabama,2010,177510.7,33848.0,41709.0,89.783
3,Alabama,2011,182896.7,34884.0,41819.0,90.011
4,Alabama,2012,188280.7,35559.0,41592.0,90.559


In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   State           867 non-null    str    
 1   Year            867 non-null    int64  
 2   GDP             867 non-null    float64
 3   Income_pc       867 non-null    float64
 4   Real_Income_pc  867 non-null    float64
 5   RPP             867 non-null    float64
dtypes: float64(4), int64(1), str(1)
memory usage: 40.8 KB


In [33]:
df["State"].nunique(), df["Year"].nunique()

(51, 17)

In [34]:
df.shape

(867, 6)

In [35]:
df.groupby("State")["Year"].count()

State
Alabama                 17
Alaska                  17
Arizona                 17
Arkansas                17
California              17
Colorado                17
Connecticut             17
Delaware                17
District of Columbia    17
Florida                 17
Georgia                 17
Hawaii                  17
Idaho                   17
Illinois                17
Indiana                 17
Iowa                    17
Kansas                  17
Kentucky                17
Louisiana               17
Maine                   17
Maryland                17
Massachusetts           17
Michigan                17
Minnesota               17
Mississippi             17
Missouri                17
Montana                 17
Nebraska                17
Nevada                  17
New Hampshire           17
New Jersey              17
New Mexico              17
New York                17
North Carolina          17
North Dakota            17
Ohio                    17
Oklahoma              

In [36]:
df.duplicated(subset=["State", "Year"]).sum()

np.int64(0)

In [39]:
pd.options.display.float_format = '{:,.0f}'.format

In [40]:
df.describe()

,Year,GDP,Income_pc,Real_Income_pc,RPP
count,867,867,867,867,867
mean,"2,016","387,286","51,314","51,366",98
std,5,"506,742","13,075","7,771",7
min,"2,008","26,140","30,220","35,790",85
25%,"2,012","94,266","41,158","45,706",92
50%,"2,016","234,022","48,578","50,686",97
75%,"2,020","466,581","59,220","56,142",102
max,"2,024","4,048,108","111,185","81,872",114


In [41]:
df.columns = df.columns.str.lower()

In [43]:
print(df.columns)

Index(['state', 'year', 'gdp', 'income_pc', 'real_income_pc', 'rpp'], dtype='str')


In [44]:
df.head()

,state,year,gdp,income_pc,real_income_pc,rpp
0,Alabama,2008,"174,666","33,441","42,219",89
1,Alabama,2009,"170,876","32,717","41,966",88
2,Alabama,2010,"177,511","33,848","41,709",90
3,Alabama,2011,"182,897","34,884","41,819",90
4,Alabama,2012,"188,281","35,559","41,592",91


In [46]:
pd.options.display.float_format = '{:,.2f}'.format

In [49]:
df.describe()

,year,gdp,income_pc,real_income_pc,rpp
count,867.00,867.00,867.00,867.00,867.00
mean,"2,016.00","387,285.55","51,314.05","51,366.15",97.50
std,4.90,"506,742.05","13,075.49","7,770.85",6.94
min,"2,008.00","26,140.40","30,220.00","35,790.00",85.02
25%,"2,012.00","94,266.05","41,158.50","45,706.50",91.84
50%,"2,016.00","234,022.20","48,578.00","50,686.00",96.72
75%,"2,020.00","466,580.60","59,219.50","56,142.00",102.41
max,"2,024.00","4,048,108.10","111,185.00","81,872.00",114.24


In [50]:
df.to_csv("../data/processed/master_dataset_v1.csv", index=False)